# Generated by Django 4.1.3 on 2023-05-23 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drone', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('code', models.CharField(max_length=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drone', to='drone.drone')),
            ],
        ),
    ]
