# Generated by Django 4.1.3 on 2023-05-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('serial_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('drone_model', models.CharField(choices=[('LIGHTWEIGHT', 'LIGHTWEIGHT'), ('MIDDLEWEIGHT', 'MIDDLEWEIGHT'), ('CRUISERWEIGHT', 'CRUISERWEIGHT'), ('HEAVYWEIGHT', 'HEAVYWEIGHT')], max_length=13)),
                ('weight_limit', models.DecimalField(decimal_places=1, max_digits=4)),
                ('battery_capacity', models.IntegerField()),
                ('state', models.CharField(choices=[('IDLE', 'IDLE'), ('LOADING', 'LOADING'), ('LOADED', 'LOADED'), ('DELIVERING', 'DELIVERING'), ('DELIVERED', 'DELIVERED'), ('RETURNING', 'RETURNING')], default='IDLE', max_length=13)),
            ],
        ),
    ]
